version: '3.8'

services:

    db:
        image: mysql:8.0
        restart: unless-stopped
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: '12345'
            MYSQL_DATABASE: 'movie_db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: '12345'
        ports:
            - '3306:3306'
        expose:
            -   '3306'
        volumes:
            - my_db:/var/lib/mysql/
#    app:
#        depends_on:
#          - postgres
#        build:
#            context: .
#            dockerfile: Dockerfile
#        image: 'app'
#        restart: on-failure
#        env_file:
#          - .env
#        ports:
#            - 8080:8080
#        environment:
#            SPRING_APPLICATION_JSON: '{
#                    "spring.datasource.url"  : "jdbc:postgresql://postgresdb:5432/$POSTGRESDB_DATABASE",
#                    "spring.datasource.username" : "$POSTGRESDB_USER",
#                    "spring.datasource.password" : "$POSTGRESDB_ROOT_PASSWORD",
#                    "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.PostgreSQLDialect",
#                    "spring.jpa.hibernate.ddl-auto" : "update",
#                    "spring.jpa.properties.hibernate.show_sql"=true
#            }'
#        volumes:
#          - .m2:/root/.m2
#        stdin_open: true
#        tty: true

#    postgres:
#        image: postgres
#        restart: unless-stopped
#        env_file:
#          - .env
#        environment:
#            - POSTGRES_PASSWORD=123456
#            - POSTGRES_DB=movie_db
#        ports:
#            - 5432:5432
#        volumes:
#            - db:/var/lib/postgresql/data



volumes:
    my_db: